name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener codigo
        uses: actions/checkout@v4

      - name: Descomprimir proyecto
        run: |
          for f in *.zip; do
            if [ -f "$f" ]; then
              echo "Descomprimiendo $f..."
              unzip -o "$f"
            fi
          done

      - name: Preparar Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Preparar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'
          cache-disabled: true

      - name: Compilar APK
        run: |
          PROJECT_DIR=$(dirname $(find . -name "settings.gradle.kts" | head -n 1))
          echo "Entrando a: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          
          # Forzamos la compatibilidad de librerias 
          gradle assembleDebug --warning-mode all
        
      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: PornBlocker-APK
          path: '**/app-debug.apk'
